var config={lattice_width:200,lattice_height:80},boltzmann=boltzmann||{},boltzmann=function(a){var r=document.getElementById("boltzmann"),n=a.lattice_width;return{lattice_width:n,lattice_height:a.lattice_height,lattice:[],queue:[],viscosity:0.02,omega:1/0.56,draw_mode:0,flow_vectors:!1,new_barrier:!0,flow_particles:[],animation_id:null,boltzcanvas:r,vectorcanvas:document.getElementById("vectorcanvas"),particlecanvas:document.getElementById("particlecanvas"),barriercanvas:document.getElementById("barriercanvas"),
boltzctx:null,vectorctx:null,particlectx:null,barrierctx:null,steps_per_frame:10,px_per_node:Math.floor(r.width/n)}}(config);
(function(){for(var a=0,r=["webkit","moz"],n=0;n<r.length&&!window.requestAnimationFrame;++n)window.requestAnimationFrame=window[r[n]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[r[n]+"CancelAnimationFrame"]||window[r[n]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(n,r){var p=(new Date).getTime(),k=Math.max(0,16-(p-a)),q=window.setTimeout(function(){n(p+k)},k);a=p+k;return q});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(a){clearTimeout(a)})})();boltzmann=boltzmann||{};
boltzmann=function(a){a.drawing=function(){function r(){for(var b=0;b<l;b++)for(var a=0;a<e;a++)y[b][a].barrier&&(x.beginPath(),x.rect(b*f,a*f,f,f),x.fill(),x.closePath())}function n(b,a,c){var g=(a+c)/2,h=Math.abs(c-g),e={r:0,g:0,b:0,a:0};b>c&&(b=c);b<a&&(b=a);b>=g?e.r=255:e.g=255;e.a=Math.floor(Math.abs(b)*(1/h)*255);return e}function D(b,a,c){var e=(c-a)/2,g=0,h=Math.round(0);b>=e?(a=255,g=Math.round((c-b)/(c-e)*255)):(g=255,a=Math.round((b-a)/(e-a)*255));return{r:a,g:g,b:h,a:255}}function w(b,
a,c){if(0==a)c=a=b=c;else{var e=function(b,a,c){0>c&&(c+=1);1<c&&(c-=1);return c<1/6?b+6*(a-b)*c:0.5>c?a:c<2/3?b+(a-b)*(2/3-c)*6:b},g=0.5>c?c*(1+a):c+a-c*a,h=2*c-g;c=e(h,g,b+1/3);a=e(h,g,b);b=e(h,g,b-1/3)}return{r:Math.round(255*c),g:Math.round(255*a),b:Math.round(255*b),a:255}}function n(b,a,c){b-=a/(c-a);return w(1-b,1,b/2)}var p={},k=a.boltzcanvas,q=a.vectorcanvas,d=a.particlecanvas,B=a.barriercanvas,z,u,v,x,f=a.px_per_node,y=a.lattice,c=a.flow_particles,l=a.lattice_width,e=a.lattice_height,g=
k.width,b=k.height,m,h,G;k.getContext?(a.boltzctx=k.getContext("2d"),a.vectorctx=q.getContext("2d"),a.particlectx=d.getContext("2d"),a.barrierctx=B.getContext("2d"),z=a.boltzctx,u=a.vectorctx,v=a.particlectx,x=a.barrierctx,u.strokeStyle="red",u.fillStyle="red",v.strokeStyle="green",v.fillStyle="green",x.fillStyle="yellow",m=z.createImageData(g,b),h=m.data,G=m.width):console.log("This browser does not support canvas");p.draw=function(){var d=a.draw_mode;a.flow_vectors&&u.clearRect(0,0,g,b);if(0<c.length){v.clearRect(0,
0,g,b);for(var s=0,k=c.length;s<k;s++){var p=c[s].x,t=c[s].y,q=v;q.beginPath();q.arc(p*f,t*f,1,0,2*Math.PI,!1);q.fill();q.closePath()}}a.new_barrier&&(x.clearRect(0,0,g,b),r(x),a.new_barrier=!1);for(s=0;s<l;s++)for(k=0;k<e;k++)if(!y[s][k].barrier){p={r:0,g:0,b:0,a:0};t=y[s][k].ux;q=y[s][k].uy;if(a.flow_vectors&&0===s%10&&0===k%10){var w=t,B=q,C=u,H=s*f,I=k*f;C.beginPath();C.moveTo(H,I);C.lineTo(Math.round(H+w*f*200),I+B*f*200);C.stroke();C.beginPath();C.arc(H,I,1,0,2*Math.PI,!1);C.fill();C.closePath()}if(0===
d)p=Math.sqrt(Math.pow(t,2)+Math.pow(q,2)),p=D(p,0,0.1);else if(1==d)p=n(5*t,-0.09,0.03);else if(2==d)p=n(5*q,-0.09,0.03);else if(3==d)p=D(y[s][k].density,0.9,3);else if(4==d)p=n(5*y[s][k].curl,-0.1,0.03);else if(5==d)continue;for(t=k*f;t<(k+1)*f;t++)for(q=s*f;q<(s+1)*f;q++)w=4*(q+t*G),h[w+0]=p.r,h[w+1]=p.g,h[w+2]=p.b,h[w+3]=p.a}z.putImageData(m,0,0)};p.clear=function(){m=z.createImageData(g,b);h=m.data;G=m.width;u.clearRect(0,0,g,b);v.clearRect(0,0,g,b);z.clearRect(0,0,g,b);x.clearRect(0,0,g,b);
r();a.new_barrier=!1};return p}();return a}(boltzmann);boltzmann=boltzmann||{};
boltzmann=function(a){a.events=function(){function r(f){if(1===(f.which||f.button)&&a.animation_id){var y=f.hasOwnProperty("offsetX")?f.offsetX:f.layerX,c=f.hasOwnProperty("offsetY")?f.offsetY:f.layerY,l=function(a){var b=a.hasOwnProperty("offsetX")?a.offsetX:a.layerX;a=a.hasOwnProperty("offsetY")?a.offsetY:a.layerY;var e=(b-y)/k/B,h=(a-c)/k/B;0.1<Math.abs(e)&&(e=0.1*Math.abs(e)/e);0.1<Math.abs(h)&&(h=0.1*Math.abs(h)/h);for(var l=Math.floor(b/k),f=Math.floor(a/k),d=-5;5>=d;d++)for(var n=-5;5>=n;n++)0<=
l+d&&l+d<D&&0<=f+n&&f+n<w&&!p[l+d][f+n].barrier&&5>Math.sqrt(d*d+n*n)&&q.push([l+d,f+n,e,h]);y=b;c=a},e=function(a){d.removeEventListener("mousemove",l,!1);d.removeEventListener("mouseup",e,!1);d.removeEventListener("touchmove",l,!1);document.body.removeEventListener("touchend",e,!1)};d.addEventListener("mousemove",l,!1);d.addEventListener("mouseup",e,!1);d.addEventListener("touchmove",l,!1);document.body.addEventListener("touchend",e,!1)}}function n(d){window.cancelAnimationFrame(a.animation_id);
a.animation_id=null;d.innerHTML="Start"}var D=a.lattice_width,w=a.lattice_height,p=a.lattice,k=a.px_per_node,q=a.queue,d=a.boltzcanvas,B=a.steps_per_frame,z=a.flow_particles,u,v,x;d.addEventListener("mousedown",r,!1);d.addEventListener("touchstart",r,!1);d.addEventListener("contextmenu",function(f){f.preventDefault();var y=f.hasOwnProperty("offsetX")?f.offsetX:f.layerX,c=f.hasOwnProperty("offsetY")?f.offsetY:f.layerY,l=Math.floor(y/k),e=Math.floor(c/k),g=!0;p[l][e].barrier&&(g=!1);p[l][e].barrier=
g;var b=function(b){y=b.hasOwnProperty("offsetX")?b.offsetX:b.layerX;c=b.hasOwnProperty("offsetY")?b.offsetY:b.layerY;l=Math.floor(y/k);e=Math.floor(c/k);p[l][e].barrier=g;a.new_barrier=!0;a.animation_id||a.drawing.draw()},m=function(a){d.removeEventListener("mousemove",b,!1);d.removeEventListener("mouseup",m,!1);d.removeEventListener("touchmove",b,!1);document.body.removeEventListener("touchend",m,!1)};d.addEventListener("mousemove",b,!1);d.addEventListener("mouseup",m,!1);d.addEventListener("touchmove",
b,!1);document.body.addEventListener("touchend",m,!1)},!1);document.getElementById("drawmode").addEventListener("change",function(d){a.draw_mode=this.selectedIndex;5==a.draw_mode&&a.drawing.clear()},!1);document.getElementById("viscosity").addEventListener("input",function(d){a.viscosity=parseInt(this.value,10)/100;a.omega=1/(3*a.viscosity+0.5)},!1);document.getElementById("speed").addEventListener("input",function(d){a.steps_per_frame=parseInt(this.value,10)},!1);v=document.getElementById("flowvectors");
v.addEventListener("click",function(f){this.checked?a.flow_vectors=!0:(a.flow_vectors=!1,a.vectorctx.clearRect(0,0,d.width,d.height))},!1);x=document.getElementById("flowparticles");x.addEventListener("click",function(f){if(this.checked)for(f=z.length=0;20>f;f++)for(var k=0;8>k;k++)p[10*f][10*k].barrier||z.push({x:10*f,y:10*k});else z.length=0,a.particlectx.clearRect(0,0,d.width,d.height)},!1);u=document.getElementById("play");u.addEventListener("click",function(d){a.animation_id?n(this):(a.queue.length=
0,a.main.updater(),this.innerHTML="Pause")},!1);document.getElementById("reset").addEventListener("click",function(d){n(u);a.flow_vectors=!1;a.flow_particles.length=0;v.checked=!1;x.checked=!1;a.main.init();a.drawing.clear()},!1);document.getElementById("clearbarriers").addEventListener("click",function(d){a.main.init_barrier([]);a.drawing.clear()},!1)}();return a}(boltzmann);boltzmann=boltzmann||{};
boltzmann=function(a){a.main=function(){function r(){this.distribution=[0,0,0,0,0,0,0,0,0];this.stream=[0,0,0,0,0,0,0,0,0];this.uy=this.ux=this.density=0;this.barrier=!1;this.curl=0}function n(a){if(void 0!==a){for(var c=0;c<k;c++)for(var l=0;l<q;l++)d[c][l].barrier=!1;for(c=0;c<a.length;c++)d[bar[c].x][bar[c].y].barrier=!0}else for(c=0;c<k;c++)for(l=0;l<q;l++)if(0===c||c===k-1||0===l||l===q-1||10>Math.abs(k/2-c)&&10>Math.abs(q/2-l))d[c][l].barrier=!0}function D(a,c,d){var e=[],g=3*a,b=3*c,k=a*a,
h=c*c;a=2*a*c;c=k+h;var f=1.5*c;e[0]=z*d*(1-f);e[1]=u*d*(1+g+4.5*k-f);e[2]=u*d*(1-b+4.5*h-f);e[3]=u*d*(1-g+4.5*k-f);e[4]=u*d*(1+b+4.5*h-f);e[5]=v*d*(1+g-b+4.5*(c-a)-f);e[6]=v*d*(1-g-b+4.5*(c+a)-f);e[7]=v*d*(1-g+b+4.5*(c-a)-f);e[8]=v*d*(1+g+b+4.5*(c+a)-f);return e}var w={},p=a.queue,k=a.lattice_width,q=a.lattice_height,d=a.lattice,B=a.flow_particles,z=4/9,u=1/9,v=1/36,x={0:{x:0,y:0},1:{x:1,y:0},2:{x:0,y:-1},3:{x:-1,y:0},4:{x:0,y:1},5:{x:1,y:-1},6:{x:-1,y:-1},7:{x:-1,y:1},8:{x:1,y:1}},f={0:0,1:3,2:4,
3:1,4:2,5:7,6:8,7:5,8:6};w.updater=function(){for(var n=a.steps_per_frame,c,l=0;l<n;l++){for(c=0;c<k;c++)for(var e=0;e<q;e++){var g=d[c][e];if(!g.barrier)for(var b=0;9>b;b++){var m=x[b],h=m.x+c,m=m.y+e;0<=h&&h<k&&0<=m&&m<q&&(d[h][m].barrier?d[c][e].stream[f[b]]=g.distribution[b]:d[h][m].stream[b]=g.distribution[b])}}c=a.omega;for(e=0;e<k;e++)for(g=0;g<q;g++)if(m=d[e][g],!m.barrier){b=m.distribution;for(h=0;9>h;h++)b[h]=m.stream[h];var h=b[0]+b[1]+b[2]+b[3]+b[4]+b[5]+b[6]+b[7]+b[8],r=(b[1]+b[5]+b[8]-
b[3]-b[6]-b[7])/h,A=(b[4]+b[7]+b[8]-b[2]-b[5]-b[6])/h;m.density=h;m.ux=r;m.uy=A;4==a.draw_mode&&0<e&&e<k-1&&0<g&&g<q-1&&(m.curl=d[e+1][g].uy-d[e-1][g].uy-d[e][g+1].ux+d[e][g-1].ux);var m=3*r,s=3*A,E=r*r,F=A*A,r=2*r*A,A=E+F,t=1.5*A;b[0]+=c*(z*h*(1-t)-b[0]);b[1]+=c*(u*h*(1+m+4.5*E-t)-b[1]);b[2]+=c*(u*h*(1-s+4.5*F-t)-b[2]);b[3]+=c*(u*h*(1-m+4.5*E-t)-b[3]);b[4]+=c*(u*h*(1+s+4.5*F-t)-b[4]);b[5]+=c*(v*h*(1+m-s+4.5*(A-r)-t)-b[5]);b[6]+=c*(v*h*(1-m-s+4.5*(A+r)-t)-b[6]);b[7]+=c*(v*h*(1-m+s+4.5*(A-r)-t)-b[7]);
b[8]+=c*(v*h*(1+m+s+4.5*(A+r)-t)-b[8])}if(0<B.length)for(c=0,e=B.length;c<e;c++)g=B[c],b=Math.floor(g.x),h=Math.floor(g.y),0<=b&&b<k&&0<=h&&h<q&&(b=d[b][h],h=b.uy,g.x+=b.ux,g.y+=h);for(;0<p.length;)c=p.shift(),e=d[c[0]][c[1]],e.distribution=D(c[2],c[3],e.density)}a.drawing.draw();a.animation_id=requestAnimationFrame(w.updater)};w.init=function(){for(var f=k,c=q,l=0;l<f;l++){d[l]=[];for(var e=0;e<c;e++)d[l][e]=new r}n([]);for(f=0;f<k;f++)for(c=0;c<q;c++)l=d[f][c],l.barrier||(l.density=1,l.ux=0,l.uy=
0,e=D(0,0,1),l.distribution=e.slice(0),l.stream=e.slice(0));p.length=0;a.drawing.draw()};w.init_barrier=n;return w}();return a}(boltzmann);boltzmann.main.init();
