var config={lattice_width:200,lattice_height:80},boltzmann=boltzmann||{},boltzmann=function(a){var q=document.getElementById("boltzmann"),m=a.lattice_width;return{lattice_width:m,lattice_height:a.lattice_height,lattice:[],queue:[],viscosity:0.02,omega:1/0.56,draw_mode:0,flow_vectors:!1,new_barrier:!0,flow_particles:[],animation_id:null,canvas:q,vectorcanvas:document.getElementById("vectorcanvas"),particlecanvas:document.getElementById("particlecanvas"),barriercanvas:document.getElementById("barriercanvas"),
steps_per_frame:10,px_per_node:Math.floor(q.width/m)}}(config);
(function(){for(var a=0,q=["webkit","moz"],m=0;m<q.length&&!window.requestAnimationFrame;++m)window.requestAnimationFrame=window[q[m]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[q[m]+"CancelAnimationFrame"]||window[q[m]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(m,q){var s=(new Date).getTime(),g=Math.max(0,16-(s-a)),r=window.setTimeout(function(){m(s+g)},g);a=s+g;return r});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(a){clearTimeout(a)})})();boltzmann=boltzmann||{};
boltzmann=function(a){a.drawing=function(){function q(a){for(var b=0;b<y;b++)for(var c=0;c<z;c++)w[b][c].barrier&&(a.beginPath(),a.rect(b*d,c*d,d,d),a.fill(),a.closePath())}function m(a,b,c){var h=(b+c)/2,e=Math.abs(c-h),f={r:0,g:0,b:0,a:0};a>c&&(a=c);a<b&&(a=b);a>=h?f.r=255:f.g=255;f.a=Math.floor(Math.abs(a)*(1/e)*255);return f}var v={},t=a.canvas,s=a.vectorcanvas,g=a.particlecanvas,r=a.barriercanvas,d=a.px_per_node,w=a.lattice,B=a.flow_particles,y=a.lattice_width,z=a.lattice_height,u=t.width,k=
t.height,A,c,f,e;a.canvas.getContext?(A=t.getContext("2d"),c=s.getContext("2d"),f=g.getContext("2d"),e=r.getContext("2d"),c.strokeStyle="red",c.fillStyle="red",f.strokeStyle="green",f.fillStyle="green",e.fillStyle="yellow"):console.log("This browser does not support canvas");v.draw=function(){var n=a.draw_mode;a.flow_vectors&&c.clearRect(0,0,u,k);if(0<B.length){f.clearRect(0,0,u,k);for(var b=0,p=B.length;b<p;b++){var h=B[b].x,l=B[b].y,g=f;g.beginPath();g.arc(h*d,l*d,1,0,2*Math.PI,!1);g.fill();g.closePath()}}a.new_barrier&&
(e.clearRect(0,0,u,k),q(e),a.new_barrier=!1);p=A.createImageData(u,k);for(b=0;b<y;b++)for(h=0;h<z;h++)if(!w[b][h].barrier){var l={r:0,g:0,b:0,a:0},g=w[b][h].ux,r=w[b][h].uy;if(a.flow_vectors&&0===b%10&&0===h%10){var C=g,s=r,x=c,t=b*d,v=h*d;x.beginPath();x.moveTo(t,v);x.lineTo(Math.round(t+C*d*200),v+s*d*200);x.stroke();x.beginPath();x.arc(t,v,1,0,2*Math.PI,!1);x.fill();x.closePath()}if(0===n)l=Math.sqrt(Math.pow(g,2)+Math.pow(r,2)),l={r:0,a:Math.floor(4E3*l),b:0,g:255},255<l.g&&(l.g=255),0>l.g&&(l.g=
0);else if(1==n)l=m(g,-0.04,0.04);else if(2==n)l=m(r,-0.04,0.04);else if(3==n)l={r:0,a:Math.floor(20*(255-255/Math.abs(w[b][h].density))),b:0,g:255},255<l.g&&(l.g=255),0>l.g&&(l.g=0);else if(4==n)l=m(w[b][h].curl,-0.1,0.1);else if(5==n)continue;g=b;r=h;C=p;for(s=r*d;s<(r+1)*d;s++)for(x=g*d;x<(g+1)*d;x++)t=4*(x+s*C.width),C.data[t+0]=l.r,C.data[t+1]=l.g,C.data[t+2]=l.b,C.data[t+3]=l.a}A.putImageData(p,0,0)};v.clear=function(){c.clearRect(0,0,u,k);particlectxclearRect(0,0,u,k);A.clearRect(0,0,u,k);
e.clearRect(0,0,u,k);q(e);a.new_barrier=!1};return v}();return a}(boltzmann);boltzmann=boltzmann||{};
boltzmann=function(a){a.events=function(){function q(k){if(1===(k.which||k.button)&&a.animation_id){var A=k.hasOwnProperty("offsetX")?k.offsetX:k.layerX,c=k.hasOwnProperty("offsetY")?k.offsetY:k.layerY,f=function(a){var b=a.hasOwnProperty("offsetX")?a.offsetX:a.layerX;a=a.hasOwnProperty("offsetY")?a.offsetY:a.layerY;var e=(b-A)/g/w,f=(a-c)/g/w;0.1<Math.abs(e)&&(e=0.1*Math.abs(e)/e);0.1<Math.abs(f)&&(f=0.1*Math.abs(f)/f);for(var d=Math.floor(b/g),k=Math.floor(a/g),m=-5;5>=m;m++)for(var q=-5;5>=q;q++)0<=
d+m&&d+m<v&&0<=k+q&&k+q<t&&!s[d+m][k+q].barrier&&5>Math.sqrt(m*m+q*q)&&r.push([d+m,k+q,e,f]);A=b;c=a},e=function(a){d.removeEventListener("mousemove",f,!1);d.removeEventListener("mouseup",e,!1);d.removeEventListener("touchmove",f,!1);document.body.removeEventListener("touchend",e,!1)};d.addEventListener("mousemove",f,!1);d.addEventListener("mouseup",e,!1);d.addEventListener("touchmove",f,!1);document.body.addEventListener("touchend",e,!1)}}function m(d){window.cancelAnimationFrame(a.animation_id);
a.animation_id=null;d.innerHTML="Start"}var v=a.lattice_width,t=a.lattice_height,s=a.lattice,g=a.px_per_node,r=a.queue,d=a.canvas,w=a.steps_per_frame,B=a.flow_particles,y,z,u;d.addEventListener("mousedown",q,!1);d.addEventListener("touchstart",q,!1);d.addEventListener("contextmenu",function(k){k.preventDefault();var A=k.hasOwnProperty("offsetX")?k.offsetX:k.layerX,c=k.hasOwnProperty("offsetY")?k.offsetY:k.layerY,f=Math.floor(A/g),e=Math.floor(c/g),n=!0;s[f][e].barrier&&(n=!1);s[f][e].barrier=n;var b=
function(b){A=b.hasOwnProperty("offsetX")?b.offsetX:b.layerX;c=b.hasOwnProperty("offsetY")?b.offsetY:b.layerY;f=Math.floor(A/g);e=Math.floor(c/g);s[f][e].barrier=n;a.new_barrier=!0;a.animation_id||a.drawing.draw()},p=function(a){d.removeEventListener("mousemove",b,!1);d.removeEventListener("mouseup",p,!1);d.removeEventListener("touchmove",b,!1);document.body.removeEventListener("touchend",p,!1)};d.addEventListener("mousemove",b,!1);d.addEventListener("mouseup",p,!1);d.addEventListener("touchmove",
b,!1);document.body.addEventListener("touchend",p,!1)},!1);document.getElementById("drawmode").addEventListener("change",function(d){a.draw_mode=this.selectedIndex},!1);document.getElementById("viscosity").addEventListener("input",function(d){a.viscosity=parseInt(this.value,10)/100;a.omega=1/(3*a.viscosity+0.5)},!1);document.getElementById("speed").addEventListener("input",function(d){a.steps_per_frame=parseInt(this.value,10)},!1);z=document.getElementById("flowvectors");z.addEventListener("click",
function(d){this.checked?a.flow_vectors=!0:(a.flow_vectors=!1,vectorcanvas.width=vectorcanvas.width)},!1);u=document.getElementById("flowparticles");u.addEventListener("click",function(d){if(this.checked)for(d=B.length=0;20>d;d++)for(var g=0;8>g;g++)s[10*d][10*g].barrier||B.push({x:10*d,y:10*g});else B.length=0,a.particlecanvas.width=a.particlecanvas.width},!1);y=document.getElementById("play");y.addEventListener("click",function(d){a.animation_id?m(this):(a.queue.length=0,a.main.updater(),this.innerHTML=
"Pause")},!1);document.getElementById("reset").addEventListener("click",function(d){m(y);a.flow_vectors=!1;a.flow_particles.length=0;z.checked=!1;u.checked=!1;a.main.init();a.drawing.clear()},!1);document.getElementById("clearbarriers").addEventListener("click",function(d){a.main.init_barrier([]);a.drawing.clear()},!1)}();return a}(boltzmann);boltzmann=boltzmann||{};
boltzmann=function(a){a.main=function(){function q(){this.distribution=[0,0,0,0,0,0,0,0,0];this.stream=[0,0,0,0,0,0,0,0,0];this.uy=this.ux=this.density=0;this.barrier=!1;this.curl=0}function m(a){if(void 0!==a){for(var c=0;c<g;c++)for(var f=0;f<r;f++)d[c][f].barrier=!1;for(c=0;c<a.length;c++)d[bar[c].x][bar[c].y].barrier=!0}else for(c=0;c<g;c++)for(f=0;f<r;f++)if(0===c||c===g-1||0===f||f===r-1||10>Math.abs(g/2-c)&&10>Math.abs(r/2-f))d[c][f].barrier=!0}function v(a,c,d){var e=[],g=3*a,b=3*c,k=a*a,
h=c*c;a=2*a*c;c=k+h;var l=1.5*c;e[0]=B*d*(1-l);e[1]=y*d*(1+g+4.5*k-l);e[2]=y*d*(1-b+4.5*h-l);e[3]=y*d*(1-g+4.5*k-l);e[4]=y*d*(1+b+4.5*h-l);e[5]=z*d*(1+g-b+4.5*(c-a)-l);e[6]=z*d*(1-g-b+4.5*(c+a)-l);e[7]=z*d*(1-g+b+4.5*(c-a)-l);e[8]=z*d*(1+g+b+4.5*(c+a)-l);return e}var t={},s=a.queue,g=a.lattice_width,r=a.lattice_height,d=a.lattice,w=a.flow_particles,B=4/9,y=1/9,z=1/36,u={0:{x:0,y:0},1:{x:1,y:0},2:{x:0,y:-1},3:{x:-1,y:0},4:{x:0,y:1},5:{x:1,y:-1},6:{x:-1,y:-1},7:{x:-1,y:1},8:{x:1,y:1}},k={0:0,1:3,2:4,
3:1,4:2,5:7,6:8,7:5,8:6};t.updater=function(){for(var m=a.steps_per_frame,c,f=0;f<m;f++){for(c=0;c<g;c++)for(var e=0;e<r;e++){var n=d[c][e];if(!n.barrier)for(var b=0;9>b;b++){var p=u[b],h=p.x+c,p=p.y+e;0<=h&&h<g&&0<=p&&p<r&&(d[h][p].barrier?d[c][e].stream[k[b]]=n.distribution[b]:d[h][p].stream[b]=n.distribution[b])}}for(c=0;c<g;c++)for(e=0;e<r;e++)if(n=d[c][e],!n.barrier){b=n.distribution;for(h=0;9>h;h++)b[h]=n.stream[h];var h=b[0]+b[1]+b[2]+b[3]+b[4]+b[5]+b[6]+b[7]+b[8],p=(b[1]+b[5]+b[8]-b[3]-b[6]-
b[7])/h,l=(b[4]+b[7]+b[8]-b[2]-b[5]-b[6])/h;n.density=h;n.ux=p;n.uy=l;4==a.draw_mode&&0<c&&c<g-1&&0<e&&e<r-1&&(n.curl=d[c+1][e].uy-d[c-1][e].uy-d[c][e+1].ux+d[c][e-1].ux);h=v(p,l,h);for(p=0;9>p;p++)l=b[p],n.distribution[p]=l+a.omega*(h[p]-l)}if(0<w.length)for(c=0,e=w.length;c<e;c++)n=w[c],b=Math.floor(n.x),h=Math.floor(n.y),0<=b&&b<g&&0<=h&&h<r&&(b=d[b][h],h=b.uy,n.x+=b.ux,n.y+=h);for(;0<s.length;)c=s.shift(),e=d[c[0]][c[1]],e.distribution=v(c[2],c[3],e.density)}a.drawing.draw();a.animation_id=requestAnimationFrame(t.updater)};
t.init=function(){for(var k=g,c=r,f=0;f<k;f++){d[f]=[];for(var e=0;e<c;e++)d[f][e]=new q}m([]);for(k=0;k<g;k++)for(c=0;c<r;c++)f=d[k][c],f.barrier||(f.density=1,f.ux=0,f.uy=0,e=v(0,0,1),f.distribution=e.slice(0),f.stream=e.slice(0));s.length=0;a.drawing.draw()};t.init_barrier=m;return t}();return a}(boltzmann);boltzmann.main.init();
