var config={lattice_width:200,lattice_height:80},boltzmann=boltzmann||{},boltzmann=function(a){var s=document.getElementById("boltzmann"),k=a.lattice_width;return{lattice_width:k,lattice_height:a.lattice_height,lattice:[],queue:[],viscosity:0.02,omega:1/0.56,draw_mode:0,flow_vectors:!1,new_barrier:!0,flow_particles:[],flow_speed:0,animation_id:null,boltzcanvas:s,vectorcanvas:document.getElementById("vectorcanvas"),particlecanvas:document.getElementById("particlecanvas"),barriercanvas:document.getElementById("barriercanvas"),
boltzctx:null,vectorctx:null,particlectx:null,barrierctx:null,steps_per_frame:10,px_per_node:Math.floor(s.width/k)}}(config);
(function(){for(var a=0,s=["webkit","moz"],k=0;k<s.length&&!window.requestAnimationFrame;++k)window.requestAnimationFrame=window[s[k]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[s[k]+"CancelAnimationFrame"]||window[s[k]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(k,s){var t=(new Date).getTime(),g=Math.max(0,16-(t-a)),p=window.setTimeout(function(){k(t+g)},g);a=t+g;return p});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(a){clearTimeout(a)})})();boltzmann=boltzmann||{};
boltzmann=function(a){a.drawing=function(){function s(){for(var b=0;b<c;b++)for(var a=0;a<f;a++)l[b][a].barrier&&(u.beginPath(),u.rect(b*w,a*w,w,w),u.fill(),u.closePath())}function k(b,a,c){var e=(a+c)/2,f=Math.abs(c-e),h={r:0,g:0,b:0,a:0};b>c&&(b=c);b<a&&(b=a);b>=e?h.r=255:h.g=255;h.a=Math.floor(Math.abs(b)*(1/f)*255);return h}function x(b,a,c){if(0==a)c=a=b=c;else{var e=function(b,a,c){0>c&&(c+=1);1<c&&(c-=1);return c<1/6?b+6*(a-b)*c:0.5>c?a:c<2/3?b+(a-b)*(2/3-c)*6:b},h=0.5>c?c*(1+a):c+a-c*a,f=
2*c-h;c=e(f,h,b+1/3);a=e(f,h,b);b=e(f,h,b-1/3)}return{r:Math.round(255*c),g:Math.round(255*a),b:Math.round(255*b),a:255}}function k(b,a,c){b-=a/(c-a);return x(1-b,1,b/2)}var A={},t=a.boltzcanvas,g=a.vectorcanvas,p=a.particlecanvas,d=a.barriercanvas,C,B,y,u,w=a.px_per_node,l=a.lattice,z=a.flow_particles,c=a.lattice_width,f=a.lattice_height,e=t.width,h=t.height,b,n,m;t.getContext?(a.boltzctx=t.getContext("2d"),a.vectorctx=g.getContext("2d"),a.particlectx=p.getContext("2d"),a.barrierctx=d.getContext("2d"),
C=a.boltzctx,B=a.vectorctx,y=a.particlectx,u=a.barrierctx,B.strokeStyle="red",B.fillStyle="red",y.strokeStyle="green",y.fillStyle="green",u.fillStyle="yellow",b=C.createImageData(e,h),n=b.data,m=b.width):console.log("This browser does not support canvas");A.draw=function(){var d=a.draw_mode;a.flow_vectors&&B.clearRect(0,0,e,h);if(0<z.length){y.clearRect(0,0,e,h);for(var r=0,q=z.length;r<q;r++){var g=z[r].x,p=z[r].y,v=y;v.beginPath();v.arc(g*w,p*w,1,0,2*Math.PI,!1);v.fill();v.closePath()}}a.new_barrier&&
(u.clearRect(0,0,e,h),s(u),a.new_barrier=!1);for(r=0;r<c;r++)for(q=0;q<f;q++)if(!l[r][q].barrier){g={r:0,g:0,b:0,a:0};p=l[r][q].ux;v=l[r][q].uy;if(a.flow_vectors&&0===r%10&&0===q%10){var t=p,A=v,x=B,F=r*w,G=q*w;x.beginPath();x.moveTo(F,G);x.lineTo(Math.round(F+t*w*200),G+A*w*200);x.stroke();x.beginPath();x.arc(F,G,1,0,2*Math.PI,!1);x.fill();x.closePath()}if(0===d)g=Math.sqrt(Math.pow(p,2)+Math.pow(v,2)),g=k(g,-0.07,0.028);else if(1==d)g=k(5*p,-0.01,0.003);else if(2==d)g=k(5*v,-0.01,0.003);else if(3==
d)g=k(l[r][q].density,-0.1,0.1);else if(4==d)g=k(5*l[r][q].curl,-0.018,0.008);else if(5==d)continue;for(p=q*w;p<(q+1)*w;p++)for(v=r*w;v<(r+1)*w;v++)t=4*(v+p*m),n[t+0]=g.r,n[t+1]=g.g,n[t+2]=g.b,n[t+3]=g.a}C.putImageData(b,0,0)};A.clear=function(){b=C.createImageData(e,h);n=b.data;m=b.width;B.clearRect(0,0,e,h);y.clearRect(0,0,e,h);C.clearRect(0,0,e,h);u.clearRect(0,0,e,h);s();a.new_barrier=!1};return A}();return a}(boltzmann);boltzmann=boltzmann||{};
boltzmann=function(a){a.events=function(){function s(l){if(1===(l.which||l.button)&&a.animation_id){var z=l.hasOwnProperty("offsetX")?l.offsetX:l.layerX,c=l.hasOwnProperty("offsetY")?l.offsetY:l.layerY,f=function(a){var b=a.hasOwnProperty("offsetX")?a.offsetX:a.layerX;a=a.hasOwnProperty("offsetY")?a.offsetY:a.layerY;var e=(b-z)/g/C,f=(a-c)/g/C;0.1<Math.abs(e)&&(e=0.1*Math.abs(e)/e);0.1<Math.abs(f)&&(f=0.1*Math.abs(f)/f);for(var d=Math.floor(b/g),l=Math.floor(a/g),q=-5;5>=q;q++)for(var k=-5;5>=k;k++)0<=
d+q&&d+q<x&&0<=l+k&&l+k<A&&!t[d+q][l+k].barrier&&5>Math.sqrt(q*q+k*k)&&p.push([d+q,l+k,e,f]);z=b;c=a},e=function(a){d.removeEventListener("mousemove",f,!1);d.removeEventListener("mouseup",e,!1);d.removeEventListener("touchmove",f,!1);document.body.removeEventListener("touchend",e,!1)};d.addEventListener("mousemove",f,!1);d.addEventListener("mouseup",e,!1);d.addEventListener("touchmove",f,!1);document.body.addEventListener("touchend",e,!1)}}function k(d){window.cancelAnimationFrame(a.animation_id);
a.animation_id=null;d.innerHTML="Start"}var x=a.lattice_width,A=a.lattice_height,t=a.lattice,g=a.px_per_node,p=a.queue,d=a.boltzcanvas,C=a.steps_per_frame,B=a.flow_particles,y,u,w;d.addEventListener("mousedown",s,!1);d.addEventListener("touchstart",s,!1);d.addEventListener("contextmenu",function(l){l.preventDefault();var z=l.hasOwnProperty("offsetX")?l.offsetX:l.layerX,c=l.hasOwnProperty("offsetY")?l.offsetY:l.layerY,f=Math.floor(z/g),e=Math.floor(c/g),h=!0;t[f][e].barrier&&(h=!1);t[f][e].barrier=
h;var b=function(b){z=b.hasOwnProperty("offsetX")?b.offsetX:b.layerX;c=b.hasOwnProperty("offsetY")?b.offsetY:b.layerY;f=Math.floor(z/g);e=Math.floor(c/g);t[f][e].barrier=h;a.new_barrier=!0;a.animation_id||a.drawing.draw()},n=function(a){d.removeEventListener("mousemove",b,!1);d.removeEventListener("mouseup",n,!1);d.removeEventListener("touchmove",b,!1);document.body.removeEventListener("touchend",n,!1)};d.addEventListener("mousemove",b,!1);d.addEventListener("mouseup",n,!1);d.addEventListener("touchmove",
b,!1);document.body.addEventListener("touchend",n,!1)},!1);document.getElementById("drawmode").addEventListener("change",function(d){a.draw_mode=this.selectedIndex;5==a.draw_mode&&a.drawing.clear()},!1);document.getElementById("viscosity").addEventListener("input",function(d){a.viscosity=parseInt(this.value,10)/100;a.omega=1/(3*a.viscosity+0.5)},!1);document.getElementById("speed").addEventListener("input",function(d){a.steps_per_frame=parseInt(this.value,10)},!1);u=document.getElementById("flowvectors");
u.addEventListener("click",function(g){this.checked?a.flow_vectors=!0:(a.flow_vectors=!1,a.vectorctx.clearRect(0,0,d.width,d.height))},!1);w=document.getElementById("flowparticles");w.addEventListener("click",function(g){if(this.checked)for(g=B.length=0;20>g;g++)for(var z=0;8>z;z++)t[10*g][10*z].barrier||B.push({x:10*g,y:10*z});else B.length=0,a.particlectx.clearRect(0,0,d.width,d.height)},!1);y=document.getElementById("play");y.addEventListener("click",function(d){a.animation_id?k(this):(a.queue.length=
0,a.main.updater(),this.innerHTML="Pause")},!1);document.getElementById("reset").addEventListener("click",function(d){k(y);a.flow_vectors=!1;a.flow_particles.length=0;u.checked=!1;w.checked=!1;a.main.init();a.drawing.clear()},!1);document.getElementById("clearbarriers").addEventListener("click",function(d){a.main.init_barrier([]);a.drawing.clear()},!1);document.getElementById("flow-speed").addEventListener("input",function(d){a.flow_speed=parseInt(this.value,10)/833},!1)}();return a}(boltzmann);boltzmann=boltzmann||{};
boltzmann=function(a){a.main=function(){function s(){this.distribution=[0,0,0,0,0,0,0,0,0];this.stream=[0,0,0,0,0,0,0,0,0];this.uy=this.ux=this.density=0;this.barrier=!1;this.curl=0}function k(a){if(void 0!==a){for(var c=0;c<g;c++)for(var f=0;f<p;f++)d[c][f].barrier=!1;for(c=0;c<a.length;c++)d[bar[c].x][bar[c].y].barrier=!0}else for(c=0;c<g;c++)for(f=0;f<p;f++)if(0===c||c===g-1||0===f||f===p-1||10>Math.abs(g/2-c)&&10>Math.abs(p/2-f))d[c][f].barrier=!0}function x(a,c,d){var e=[],h=3*a,b=3*-c,g=a*a,
m=-c*-c;a=2*a*-c;c=g+m;var k=1.5*c;e[0]=B*d*(1-k);e[1]=y*d*(1+h+4.5*g-k);e[2]=y*d*(1+b+4.5*m-k);e[3]=y*d*(1-h+4.5*g-k);e[4]=y*d*(1-b+4.5*m-k);e[5]=u*d*(1+h+b+4.5*(c+a)-k);e[6]=u*d*(1-h+b+4.5*(c-a)-k);e[7]=u*d*(1-h-b+4.5*(c+a)-k);e[8]=u*d*(1+h-b+4.5*(c-a)-k);return e}var A={},t=a.queue,g=a.lattice_width,p=a.lattice_height,d=a.lattice,C=a.flow_particles,B=4/9,y=1/9,u=1/36,w={0:{x:0,y:0},1:{x:1,y:0},2:{x:0,y:-1},3:{x:-1,y:0},4:{x:0,y:1},5:{x:1,y:-1},6:{x:-1,y:-1},7:{x:-1,y:1},8:{x:1,y:1}},l={0:0,1:3,
2:4,3:1,4:2,5:7,6:8,7:5,8:6};A.updater=function(){var k=a.steps_per_frame,c,f=a.flow_speed;for(c=0;c<g-1;c++)d[c][0].distribution=x(f,0,1),d[c][p-1].distribution=x(f,0,1);for(c=0;c<p-1;c++)d[0][c].distribution=x(f,0,1),d[g-1][c].distribution=x(f,0,1);for(f=0;f<k;f++){for(c=0;c<g;c++)for(var e=0;e<p;e++){var h=d[c][e];if(!h.barrier)for(var b=0;9>b;b++){var n=w[b],m=n.x+c,n=n.y+e;0<=m&&m<g&&0<=n&&n<p&&(d[m][n].barrier?d[c][e].stream[l[b]]=h.distribution[b]:d[m][n].stream[b]=h.distribution[b])}}c=a.omega;
for(e=1;e<g-1;e++)for(h=1;h<p-1;h++)if(n=d[e][h],!n.barrier){b=n.distribution;for(m=0;9>m;m++)b[m]=n.stream[m];var m=b[0]+b[1]+b[2]+b[3]+b[4]+b[5]+b[6]+b[7]+b[8],s=(b[1]+b[5]+b[8]-b[3]-b[6]-b[7])/m,r=(b[4]+b[7]+b[8]-b[2]-b[5]-b[6])/m;n.density=m;n.ux=s;n.uy=r;4==a.draw_mode&&0<e&&e<g-1&&0<h&&h<p-1&&(n.curl=d[e+1][h].uy-d[e-1][h].uy-d[e][h+1].ux+d[e][h-1].ux);var n=3*s,q=3*r,D=s*s,E=r*r,s=2*s*r,r=D+E,v=1.5*r;b[0]+=c*(B*m*(1-v)-b[0]);b[1]+=c*(y*m*(1+n+4.5*D-v)-b[1]);b[2]+=c*(y*m*(1-q+4.5*E-v)-b[2]);
b[3]+=c*(y*m*(1-n+4.5*D-v)-b[3]);b[4]+=c*(y*m*(1+q+4.5*E-v)-b[4]);b[5]+=c*(u*m*(1+n-q+4.5*(r-s)-v)-b[5]);b[6]+=c*(u*m*(1-n-q+4.5*(r+s)-v)-b[6]);b[7]+=c*(u*m*(1-n+q+4.5*(r-s)-v)-b[7]);b[8]+=c*(u*m*(1+n+q+4.5*(r+s)-v)-b[8])}if(0<C.length)for(c=0,e=C.length;c<e;c++)h=C[c],b=Math.floor(h.x),m=Math.floor(h.y),0<=b&&b<g&&0<=m&&m<p&&(b=d[b][m],m=b.uy,h.x+=b.ux,h.y+=m);for(;0<t.length;)c=t.shift(),e=d[c[0]][c[1]],e.distribution=x(c[2],c[3],e.density)}a.drawing.draw();a.animation_id=requestAnimationFrame(A.updater)};
A.init=function(){for(var l=g,c=p,f=d.length=0;f<l;f++){d[f]=[];for(var e=0;e<c;e++)d[f][e]=new s}k([]);for(l=0;l<g;l++)for(c=0;c<p;c++)f=d[l][c],f.barrier||(f.density=1,f.ux=0,f.uy=0,e=x(0,0,1),f.distribution=e.slice(0),f.stream=e.slice(0));t.length=0;a.drawing.draw()};A.init_barrier=k;return A}();return a}(boltzmann);boltzmann.main.init();
